### ISSUE TITLE
I get unresolvable dependencies.

### ISSUE THREAD

**Issue by mschulzeondts** [ksilz/flutter_native_ui_cross_example#1]
Hi and first let me thank you, for your sample applications and explanations.

When I start the your application I'm getting the following Error.

```
Resolving dependencies...
Because fluent_ui 4.0.3 depends on flutter_localizations from sdk which depends on intl 0.18.1, fluent_ui 4.0.3 requires intl 0.18.1.
So, because flutter_native_ui_cross_example depends on fluent_ui 4.0.3 which depends on intl ^0.17.0, version solving failed.
```

I am very new to Flutter, so I had the complete IDE (Android Studio) and the toolset freshly installed / configured. I would like to claim that the error shown is a general error and points to a wrong dependency tree.

Am I correct in this?
Can you correct this?

Best regards

**Comment by Gsuyash20** [comment]
@mschulzeondts update the fluent_ui package as currently 4.6.1 is out. You can check on pub.dev

**Comment by ksilz** [comment]
@mschulzeondts Thank you! I'll update it to the latest version of Flutter in the next few days.

**Comment by ksilz** [comment]
@mschulzeondts Please try if it works now. I tested with Flutter 3.10.5.

**Comment by mschulzeondts** [comment]
Thank you very much. I will check it shortly - unfortunately I am quite busy at the moment.
